<?php
declare(strict_types=1);
/**
 * All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block GingerPay\Payment\Block\Adminhtml\Render\Header
 */
?>
<div class="mm-block-ginger">
    <a class="helpbutton" target="_blank"></a>
    <p>
        <?= $block->escapeHtml(__('NoPayn helps entrepreneurs with the best, smartest and most efficient payment systems.')) ?>
    </p>
    <table>
        <tbody>
            <tr>
                <td>
                    <div class="icon1"></div>
                    <a href="https://www.nopayn.io/" target="_blank">
                    <?= $block->escapeHtml(__('Visit nopayn.io')) ?>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
